#!/bin/sh
mvn clean package && docker build -t test/payarajakarta .
docker rm -f payarajakarta 2>/dev/null || true && docker run -it --name payarajakarta -p 8080:8080 -p 4848:4848 -p 8181:8181 --name payarajakarta test/payarajakarta
